/**
 * `dokomade remove` - undo what `init` wrote to this project.
 *
 * The hooks come off first: they are what keeps writing rows, and an install
 * that was half-removed but still fires on every edit is worse than one nobody
 * touched. Only groups `init` wrote are dropped, so a project that registered
 * its own hooks next to dokomade's keeps them.
 *
 * `.gitignore` is deliberately left alone. init's block also ignores `.env`,
 * and tidying that rule away during an uninstall would put a secrets file back
 * into the next commit.
 */
import fs from "node:fs"
import path from "node:path"
import readline from "node:readline/promises"
import { STATE_DIR, findRoot, paths, readConfig, readJSON, safeRelativePath, writeJSON } from "../core/store.js"
import { WORKFLOW_FILE } from "../core/workflow.js"
import { isOurHandler, isOurs, type CursorHooks, type Settings } from "./init.js"

export interface RemoveOptions {
  /** Also delete the log directory. Off by default - the logs are the user's history, not our state. */
  logs?: boolean
  yes?: boolean
}

/** The first line every generated workflow carries; a hand-written one must survive. */
const WORKFLOW_MARKER = "Generated by `dokomade connect`"

async function confirm(question: string): Promise<boolean> {
  // Nothing to ask without a terminal: `remove` was typed on purpose.
  if (!process.stdin.isTTY || !process.stdout.isTTY) return true
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  try {
    const answer = (await rl.question(`${question} [Y/n] `)).trim().toLowerCase()
    return answer === "" || answer === "y" || answer === "yes"
  } finally {
    rl.close()
  }
}

/** Drop our groups from a Claude Code / Codex hook file. Returns true when it changed. */
function stripHookFile(file: string): boolean {
  const settings = readJSON<Settings | null>(file, null)
  if (!settings?.hooks) return false

  let changed = false
  for (const event of Object.keys(settings.hooks)) {
    const groups = settings.hooks[event] ?? []
    const kept = groups.filter((group) => !isOurs(group))
    if (kept.length === groups.length) continue
    changed = true
    if (kept.length > 0) settings.hooks[event] = kept
    else delete settings.hooks[event]
  }
  if (!changed) return false

  if (Object.keys(settings.hooks).length === 0) delete settings.hooks
  // A file holding nothing but our hooks is init's own leftover, not the user's.
  if (Object.keys(settings).length === 0) fs.rmSync(file, { force: true })
  else writeJSON(file, settings)
  return true
}

/** Same, for Cursor's flatter file: an event maps straight to a list of handlers. */
function stripCursorFile(file: string): boolean {
  const config = readJSON<CursorHooks | null>(file, null)
  if (!config?.hooks) return false

  let changed = false
  for (const event of Object.keys(config.hooks)) {
    const handlers = config.hooks[event] ?? []
    const kept = handlers.filter((handler) => !isOurHandler(handler))
    if (kept.length === handlers.length) continue
    changed = true
    if (kept.length > 0) config.hooks[event] = kept
    else delete config.hooks[event]
  }
  if (!changed) return false

  if (Object.keys(config.hooks).length === 0) delete config.hooks
  // `version` on its own is the header init wrote, not a file worth keeping.
  if (Object.keys(config).every((key) => key === "version")) fs.rmSync(file, { force: true })
  else writeJSON(file, config)
  return true
}

export async function remove(opts: RemoveOptions = {}, cwd: string = process.cwd()): Promise<void> {
  const root = findRoot(cwd)
  if (!root) {
    console.error("remove: dokomade is not initialised here.")
    process.exitCode = 1
    return
  }

  const p = paths(root)
  const config = readConfig(p)
  const logDir = path.join(root, safeRelativePath(config.logDir, "docs/dokomade"))
  const logsExist = fs.existsSync(logDir)
  const logDirLabel = path.relative(root, logDir) || "docs/dokomade"

  if (!opts.yes) {
    const extra = opts.logs && logsExist ? ` and delete ${logDirLabel}/` : ""
    if (!(await confirm(`Remove dokomade hooks and ${STATE_DIR}/ from ${root}${extra}?`))) {
      console.log("remove: cancelled.")
      process.exitCode = 1
      return
    }
  }

  const removed: string[] = []
  if (stripHookFile(path.join(root, ".claude", "settings.json"))) removed.push(".claude/settings.json")
  if (stripHookFile(path.join(root, ".codex", "hooks.json"))) removed.push(".codex/hooks.json")
  if (stripCursorFile(path.join(root, ".cursor", "hooks.json"))) removed.push(".cursor/hooks.json")

  if (fs.existsSync(p.dir)) {
    fs.rmSync(p.dir, { recursive: true, force: true })
    removed.push(`${STATE_DIR}/`)
  }

  try {
    const workflow = path.join(root, WORKFLOW_FILE)
    if (fs.readFileSync(workflow, "utf8").includes(WORKFLOW_MARKER)) {
      fs.rmSync(workflow, { force: true })
      removed.push(WORKFLOW_FILE)
    }
  } catch {
    // No workflow file, or one we did not generate: not ours to delete.
  }

  if (opts.logs && logsExist) {
    fs.rmSync(logDir, { recursive: true, force: true })
    removed.push(`${logDirLabel}/`)
  }

  console.log(`\ndokomade removed from ${root}`)
  for (const item of removed) console.log(`  - ${item}`)
  if (removed.length === 0) console.log("  - nothing to remove")

  console.log("\nStill to do yourself:")
  console.log("  - npm rm dokomade   (after this command, while the binary still exists)")
  console.log("  - restart Claude Code / Codex / Cursor so the removed hooks stop firing")
  console.log("  - .gitignore keeps its dokomade block, including the `.env` rule - remove it by hand if you want it gone")
  if (!opts.logs && logsExist) {
    console.log(`  - logs are kept in ${logDirLabel}/ - delete them yourself, or rerun with --logs`)
  }
  console.log("  - delete any DOKOMADE_* repository secrets or .env entries you configured\n")
}
