/**
 * The GitHub Actions workflow that runs `dokomade sync` after a push.
 *
 * Written to the project rather than shipped as a reusable action: the file
 * has to name the secrets, and a repository secret is only readable by a
 * workflow that lists it. Regenerated on every `connect`/`init` so a schema
 * change reaches projects that already have one - it carries no user edits
 * worth preserving, only the log directory it watches.
 */
import fs from "node:fs"
import path from "node:path"

export const WORKFLOW_FILE = ".github/workflows/dokomade-sync.yml"

/**
 * `github.event.before` is the sha the branch pointed at before this push,
 * which is exactly the range whose rows are new. On a branch's first push it
 * is forty zeros; sync resolves that back to HEAD~1 itself.
 *
 * `fetch-depth: 0` is not optional: checkout's default shallow clone has one
 * commit, so neither `before` nor `HEAD~1` exists and every diff would fall
 * back to "the whole log", re-sending rows as duplicate pages.
 */
function template(logDir: string): string {
  return `# Generated by \`dokomade connect\`. Sends the log rows added by a push to
# the integrations enabled in .dokomade/config.json.
name: dokomade sync

on:
  push:
    paths:
      - "${logDir}/**"
  workflow_dispatch:

concurrency:
  group: dokomade-sync-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx -y dokomade@latest sync --since "\${{ github.event.before }}"
        env:
          DOKOMADE_NOTION_TOKEN: \${{ secrets.DOKOMADE_NOTION_TOKEN }}
          DOKOMADE_NOTION_DB: \${{ secrets.DOKOMADE_NOTION_DB }}
          DOKOMADE_SHEETS_KEY: \${{ secrets.DOKOMADE_SHEETS_KEY }}
          DOKOMADE_SHEETS_ID: \${{ secrets.DOKOMADE_SHEETS_ID }}
          DOKOMADE_SHEETS_TAB: \${{ secrets.DOKOMADE_SHEETS_TAB }}
`
}

/**
 * Write the workflow. Returns true when the file changed, so the caller can
 * tell the user there is something new to commit - an uncommitted workflow
 * never runs, and that is the failure this whole path is easiest to miss.
 */
export function writeWorkflow(root: string, logDir: string): boolean {
  const file = path.join(root, WORKFLOW_FILE)
  const next = template(logDir)
  try {
    if (fs.readFileSync(file, "utf8") === next) return false
  } catch {
    // No file yet, or unreadable - either way it gets written below.
  }
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, next)
  return true
}
